Console.Clear();
Console.WriteLine("Введите координату X первой точки = ");
double x1 = double.Parse(Console.ReadLine());
Console.WriteLine("Введите координату Y первой точки = ");
double y1 = double.Parse(Console.ReadLine());
Console.WriteLine("Введите координату Z первой точки = ");
double z1 = double.Parse(Console.ReadLine());
Console.WriteLine("Введите координату X вторй точки = ");
double x2 = double.Parse(Console.ReadLine());
Console.WriteLine("Введите координату Y второй точки = ");
double y2 = double.Parse(Console.ReadLine());
Console.WriteLine("Введите координату Z второй точки = ");
double z2 = double.Parse(Console.ReadLine());
double s = Math.Sqrt(Math.Pow((x1 - x2), 2) + Math.Pow((y1 - y2), 2)+Math.Pow((z1-z2),2));
Console.WriteLine($"{s:f3}");